#define TEST_INTEGRATION_PATH "/home/vamsik1211/Downloads/gazebo/src/gazebo-10.1.0/test/integration"
#define TEST_REGRESSION_PATH "/home/vamsik1211/Downloads/gazebo/src/gazebo-10.1.0/test/regression"
#define TEST_UNIT_PATH "/home/vamsik1211/Downloads/gazebo/src/gazebo-10.1.0/test/unit"
#define TEST_PATH "/home/vamsik1211/Downloads/gazebo/src/gazebo-10.1.0/test"
#define PROJECT_SOURCE_PATH "/home/vamsik1211/Downloads/gazebo/src/gazebo-10.1.0"
#define PROJECT_BINARY_PATH "/home/vamsik1211/Downloads/gazebo/src/gazebo-10.1.0/build"
